### ISSUE TITLE
provide instructions on how to display only errors

### ISSUE THREAD

**Issue by stevenb256** [joefitzgerald/gometalinter-linter#18]
Turns on format on save, no way to see just errors (that flag doesn't seem to work), really really slow after hitting save, causes editor to flash when doing a save (probably due to format). If I disable the package, then I now no longer get build errors in atom on go files using just the go plus package.

**Comment by stevenb256** [comment]
--errors turns everything off, even compile errors. so there is no way to turn off all of the warnings and see just pure compilation errors on save anymore. bummer

**Comment by joefitzgerald** [comment]
This looks to be an issue with gometalinter. I'm sorry you're having issues. https://github.com/alecthomas/gometalinter/issues/101 tracks that issue.

I am very sensitive to - and aware of - the fact that people use my packages to achieve their work day to day, and any issues can impact your productivity. In light of that, could you please use issue titles that are worded a bit more carefully? Obviously the intent is never to create issues.

**Comment by stevenb256** [comment]
Thanks Joe. I'm very grateful to you for providing such wonderful support for Go. I've mostly figured things out. My code was not lint clean across all the new linters you added, but I still wanted the basically error style stuff around types and such at save time. --errors would be nice, but since it didn't work I had to disable a bunch of linters and supress some messages. This mostly got me back to a good state. I will eventually get lint clean, but thats a fiar bit a work right now.

**Comment by joefitzgerald** [comment]
@sbaileyms this is now fixed in gometalinter via [#103](https://github.com/alecthomas/gometalinter/pull/103). Please run `go get -u github.com/alecthomas/gometalinter` on the command line and then specify `--vendor, --fast, --errors, --json, ./...` as the args for gometalinter in `Atom` > `Preferences` > `Packages` > `gometalinter-linter` > `Settings` > `args`.

**Comment by joefitzgerald** [comment]
Oh and just to
