### ISSUE TITLE
Proposition: use the non-official convention for Linter providers

### ISSUE THREAD

**Issue by guerrero** [joefitzgerald/gometalinter-linter#2]
What do you think about rename your repo and package name to use the non-established convention that almost all of Linter providers follow (`linter-<providerName>`)? Also, it would be great to reflect into the description that this is an Atom Linter plugin.

This changes could benefit third party tools and searches made with `apm`.

**Comment by joefitzgerald** [comment]
I'm open to this. How big a deal is it that this isn't following the convention? Not sure...

**Comment by joefitzgerald** [comment]
For now, I'm just going to leave the name as-is.
