### ISSUE TITLE
Ignore file pattern

### ISSUE THREAD

**Issue by KayoticSully** [joefitzgerald/gometalinter-linter#20]
I can't find a way to ignore specific files.  I have some generated code files that gometalinter complains about but that I can't fix.  Such as asset files generated by go-bindata and ffjson files.  It is quite annoying to have warnings coming up every time I save a file in my project.  I don't want to just turn the warnings off though as I still want to see them for the code I am writing.

Is there a way to accomplish this?  Is this within the scope of this plugin to accomplish?

**Comment by joefitzgerald** [comment]
Absolutely within the scope of this plugin and [`gometalinter`](https://github.com/alecthomas/gometalinter) to ignore files. One simple solution is to replace the default args with these args: `--vendor --fast --json .` (i.e. replacing `./...` with `.`); this will only have an effect if your generated files are in a sub-package.

**Comment by KayoticSully** [comment]
They generally are not. Esp ffjson, those files need to be in the same package as the types they are being generated for.  I could probably use that technique for now with go-bindata though... Is there a way I can negate files with the path parameter ./...?  Or does it just take that path literally?

**Comment by joefitzgerald** [comment]
I'm pretty sure the `./...` is just a glob pattern. Consequently, you should have a fair bit of flexibility to modify the pattern to exclude files with names following a particular pattern.

**Comment by mvryan** [comment]
So I was able to get this functionality using the -e, --exclude flag. 
It takes a regular expression, currently I'm just using it to ignore the auto-generated files from go-bindata so have --exclude=bindata
Works like a charm.

**Comment by joefitzgerald** [comment]
If you were able to get `-e` working, would you mind weighing in on #31 ?

**Comment by joefitzgerald** [comment]
See also #31. Closing this as it's a `gometalinter` issue. The workaround is to use `--exclude='comment'`
