### ISSUE TITLE
lint not working

### ISSUE THREAD

**Issue by oldCoderException** [joefitzgerald/gometalinter-linter#21]
go-plus used to be darn good at highlighting errors in code upon save.  Saved me compiling to find them.  As of today (I upgraded to Atom 1.6 and it seemed to update go-plus significantly) it reports "No Issues" even if I type in a blatantly wrong variable name, don't use a variable, or pretty much anything.  It installed a whack of tools in my local "bin" directory on install (I have a couple of different go project folders and scripts to change the GOPATH depending on what I'm doing), so maybe something about that is screwy?  I'm using ubuntu 15.10.  But the old one worked fine.  Unfortunate.

**Comment by joefitzgerald** [comment]
This is the second report of issues in Ubuntu. Do you have time to screenshare with me so I can see the problem first hand?

**Comment by oldCoderException** [comment]
Happy to help if I can Joe.

What exactly is screenshare?  It's new to me.

For now I did include a screen capture with two errors coded at the top,
saved it, and the bottom just shows "No Issues".

First, the "testVar" is never used, so is a Go error.
Second, I purposely misspelled "dbHandler" as "dHndler" which is a name
that doesn't exist at all.  Should also be flagged as an error.

If there's something else I can do let me know and I'll try.  It did say
many tools were missing, prompted me to "go-get" things, which I let it do,
and said it installed a whole list of tools in the local bin directory in
my project workspace.

cheers,
Paul

**Comment by joefitzgerald** [comment]
Could you please confirm that `$GOPATH/bin` is in your `PATH`?

**Comment by oldCoderException** [comment]
Yup.  I confirm:
$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/go/bin:/usr/local/go_appengine

**Comment by joefitzgerald** [comment]
Ok and if you open the Chromium developer tools (ctrl-alt-i) and go to console and type `process.env` and expand the resulting node, can you paste the output?

**Comment by oldCoderException** [comment]
It's not letting me copy, so I'll have to screenshot, but some telling
"WARNINGS" up top:

**Comment by oldCoderException** [comment]
I suspect I just need to put all the tools in /usr/local/go/bin/ maybe.....

<snip>

**Comment by oldCoderException** [comment]
Did that and it's finding lots now.

**Comment by oldCoderException** [comment]
So I'm sure that was it.  Due to my using multiple Go environments and
setting things in scripts as I build, it was putting the tools in the
locale "bin" directory in that working directory.  But that working bin
directory is not on the PATH.  Once I copied it all to /usr/local/go/bin/
(where Go is installed), it worked fine.
