### ISSUE TITLE
Linter error/warning 'jewels' in the sidebar are hard to use

### ISSUE THREAD

**Issue by swsnider** [joefitzgerald/gometalinter-linter#22]
It's a lot of effort now to display the reason that a specific line was marked as having a linter error. I _think_ that I need to select all initial whitespace on a line to get it? For lines with no initial whitespace, it seems to display when I place the cursor in the leftmost position on the line?

Can this be made easier to trigger?

**Comment by joefitzgerald** [comment]
The issue here is that gometalinter returns lots of messages from linters with a 0 column index. Obviously that's sub-optimal so I will try to track down why that is the case. Ideally, for linters that support it gometalinter would provide start and end indices, allowing `linter` to highlight the entire affected area.

**Comment by swsnider** [comment]
That makes sense. However, the linter is not actually highlighting anything in the line, so it's not clear what to click on to see the error. Can you just make it so that clicking in the line shows the error or something similar?

**Comment by mathvav** [comment]
Yeah, what happens is I have to either look down at the bottom or slowly use the arrow key to move over until it shows up.

Two proposals would easily fix this:
- For liners that provide start and stop, you could have an "underlined" section that shows where the error popup shows when the cursor is there. For linters that do not specify a column (always 0), the entire line should be underlined (and, thus, a trigger for the error popup).
- You could highlight/bring to the top any errors on the currently selected line.

For an underline, I'm thinking a line with notches on the sides would increase visibility. However, this takes a lot more time to implement, so underlining would be good for me :)

**Comment by joefitzgerald** [comment]
This was fixed via #30.
