### ISSUE TITLE
--disable flag not working?

### ISSUE THREAD

**Issue by kchristidis** [joefitzgerald/gometalinter-linter#23]
The "gometalinter Arguments" section of the plugin's settings in Atom reads:

```
--disable=gocyclo, gotype --vendor --json
```

However, I keep getting warnings and errors from both the "gocyclo" and the "gotype" tool (via gometalinter) when I press save.

What am I doing wrong?

**Comment by kchristidis** [comment]
Ah, that was me being careless. Correct syntax is:

```
--disable=gocyclo, --disable=gotype, --vendor, --json
```

**Comment by joefitzgerald** [comment]
:tada: glad you got it to work. Maybe we should add some more documentation on how to configure the package?

**Comment by kchristidis** [comment]
I think the text that is in there already is good enough. (That's how I realized I was missing the commas.) So I'd say we're good.
