### ISSUE TITLE
Output ordering

### ISSUE THREAD

**Issue by tg** [joefitzgerald/gometalinter-linter#25]
I thought it would be great to see errors before warnings, so I've modified the gometaliner arguments to include `--sort` flag as follows:

```
--vendor, --fast, --json, --sort=severity
```

It seems to work correctly only on the first run though (after restarting Atom, on first save); all subsequent saves are out of order.

**Comment by joefitzgerald** [comment]
This is because linter maintains state between lint runs. The solution is to either patch linter (which doesn't seem possible at the moment) or work on an alternate linter (which is a possibility).

**Comment by tg** [comment]
Thanks, I somehow missed the UI is maintained by a different package. Will be focusing there.
