### ISSUE TITLE
Private repo import errors

### ISSUE THREAD

**Issue by davidkeeling** [joefitzgerald/gometalinter-linter#26]
My imports from a private Github repo are no longer being found by this tool (Windows 10, Go 1.4). I also had to run 'go get' again for various google.golang.org packages after updating.

**Comment by joefitzgerald** [comment]
Temporary fix: periodically run `go install ./...` in your package.

**Comment by davidkeeling** [comment]
Thanks, temporary fix works.

**Comment by GrimTheReaper** [comment]
I'm reporting the same bug (Debian 8, go 1.6), the workaround works for me too.

**Comment by joefitzgerald** [comment]
This is fixed in `go-plus` `4.1.0` https://github.com/joefitzgerald/go-plus/releases/tag/v4.1.0.
