### ISSUE TITLE
Editing file outside of GOPATH causes gometalinter to lint excessive files

### ISSUE THREAD

**Issue by lurkermike** [joefitzgerald/gometalinter-linter#27]
I noticed this evening my laptop fan was spinning pretty fast.  Turns out that gometalinter was eating up all my CPU cycles.  I believe this is because I was editing a golang file outside of my GOPATH, in the base of my home directory, and gometalinter decided to lint every file in my home directory (and below) as a result.

The reason I believe this is because, after waiting a while, at the bottom of the Atom window, the Project counter was 3700+ and clicking on it showed gometalinter results for files other than the one I'm currently working on.

This is Go 1.6 with Atom 1.6.0 and the latest go-plus.  To reproduce, just "atom file.go" from your home directory and watch gometalinter go crazy.

**Comment by joefitzgerald** [comment]
Yep, this is because the default argument for `gometalinter` is `./...`. I should probably change this to `.` so that it doesn't attempt to lint sub-packages - by default.

**Comment by joefitzgerald** [comment]
I updated the default arguments in `v1.0.4` to use `.` instead of `./...`, which should prevent this in the future.
