### ISSUE TITLE
gometalinter run although disabled in configuration

### ISSUE THREAD

**Issue by the42** [joefitzgerald/gometalinter-linter#28]
I currently have an issue with gotype not recognizing my vendored packages and thought I can disable linting altogether using the configuration of go-plus / Settings / and disable "lint on save". However it seems as gometalinter still runs as it reports linting errors.

I thought that disabling "Lint on save" should disable linting?

**Comment by joefitzgerald** [comment]
Please update to `go-plus` `v4.1.0` and ensure `builder-go` gets installed. This will fix the root cause. 

The `Lint On Save` configuration item is no longer an option in `go-plus` because linting is now triggered by [`linter`](https://atom.io/packages/linter).
