### ISSUE TITLE
linter ignores settings "dupl"

### ISSUE THREAD

**Issue by alexei-led** [joefitzgerald/gometalinter-linter#29]
I've added following lines to Atom _config_:

```
gometalinter-linter":
    args: [
      "--disable=dupl"
      "--dupl-threshold=500"
    ]
```

`gometalinter` still runs `dull` linter on my code and reports "duplicate" warning. I also tried to increase threshold - no impact.

**Comment by silentsokolov** [comment]
+1, but with `--exclude=".*comment.*"` (no best regex, but in console worked)

<img width="699" alt="2016-03-22 20 22 52" src="https://cloud.githubusercontent.com/assets/398939/13961741/ed396f1e-f06e-11e5-997a-7a0481f7b9af.png">

**Comment by joefitzgerald** [comment]
Have you updated your packages recently? You're definitely running the latest gometalinter-linter version?

**Comment by joefitzgerald** [comment]
The latest version disables dupl by default.

**Comment by alexei-led** [comment]
OK, I've updated. Seems that everything works now. I mean, I did not check if `dupl` works, but it does not annoy me anymore, so I'm happy. Thank you.
