### ISSUE TITLE
Make Package Configurable

### ISSUE THREAD

**Issue by jakebailey** [joefitzgerald/gometalinter-linter#3]
It'd be great if we could add command line flags for gometalinter.

(I'd like to be able to disable dupl, since it can be a little bit too overzealous with checking for duplicated code, but all options would be nice.)

**Comment by joefitzgerald** [comment]
Yup, totally plan to add this. I was waiting until I integrate editorconfig so you can specify per-package settings, but I suppose that is not strictly required yet.

**Comment by jakebailey** [comment]
No problem. I can ignore a yellow dot and line for now. :)

**Comment by ottob** [comment]
This would super nice, then it would be possible to enable goimports.

I guess gometalinter-linter will be the preferred way to do this in Atom?

**Comment by franklinkim** [comment]
:+1:

**Comment by joefitzgerald** [comment]
Currently working on adding config options. Will look at editorconfig integration as a separate activity.

**Comment by joefitzgerald** [comment]
This was completed in v1.0.0 (without editorconfig support).
