### ISSUE TITLE
Not passing -e argument to gometalinter

### ISSUE THREAD

**Issue by DennyLoko** [joefitzgerald/gometalinter-linter#31]
Package version: **1.0.6**
Atom version: **1.7.0-beta0** and **1.6.0**
OS: **OS X El Capitan**

I have configured gometalinter-linter to pass `--fast, --vendor, --json, -e 'comment', .` to gometalinter, but it keeps warning me about what I dont't want to be warned.

![screen shot 2016-03-23 at 13 12 10](https://cloud.githubusercontent.com/assets/635014/13991976/ee6db19e-f0f8-11e5-90ed-0ab8bebde607.png)

Using gometalinter on command-line on the same file, just works well.

![screen shot 2016-03-23 at 13 14 05](https://cloud.githubusercontent.com/assets/635014/13992039/2e169144-f0f9-11e5-9324-62912a91377d.png)

Thanks.

**Comment by mvryan** [comment]
So when working with `-e` it is a little buggy.
For some reason it is only working with`--exclude` and you have to specify with `=` and cannot use single quotes. I'm guessing this has to do with how the list of options is being processed mixed mixed with the underlying tool being a little particular.

I have the following working, `--exclude=comment`

**Comment by joefitzgerald** [comment]
Have you tried escaping the quotes?

**Comment by mvryan** [comment]
I have tried `\', \\', \", and \\"`
I have also been testing directly with gometalinter and it has an issue also;
`-e 'comment'` works, however, `-e='comment'` does not.
Both `--exclude 'comment'` and `--exclude='comment'` work.

**Comment by joefitzgerald** [comment]
That's really strange, and it sounds like a `gometalinter` bug if so. Sounds like `--exclude='comment'` is the preferred way for the time being.

**Comment by joefitzgerald** [comment]
Could you open a `gometalinter` issue and link back to this?

**Comment by joefitzgerald** [comment]
Actually sounds like `--exclude=comment` is the preferred way. The quotes appear to cause issues.
