### ISSUE TITLE
Vendored code not being seen.  

### ISSUE THREAD

**Issue by dstroot** [joefitzgerald/gometalinter-linter#32]
Cannot figure out how to get this to actually "see" I have my files vendored.  The vendor directory is there, the imported code is there in the proper places and the go code compiles and runs cleanly.  

![image](https://cloud.githubusercontent.com/assets/1438457/13992502/8ee6f290-f0d9-11e5-8a54-a4bddb1db29b.png)

How do I just turn this off so it can be usable to me?

**Comment by FrenchBen** [comment]
Same issue here - Since 1.6 update things have been pretty messy

**Comment by joefitzgerald** [comment]
The temporary workaround is to periodically run `go install ./...` from your package. The medium term solution is to have a package which does this for you and displays syntax/build issues, and to stop using `gotype`.

Medium term in this context is a couple days.

**Comment by FrenchBen** [comment]
The workaround is to install the packages as non-vendor packages?

**Comment by joefitzgerald** [comment]
No; `go install ./...` will respect the source location you won't find the vendored packages in `$GOPATH/src` as a result of running it; it simply compiles the current package's `.a` file(s) to `$GOPATH/pkg`.

**Comment by FrenchBen** [comment]
Thanks for the clarification. Read it as a `get` instead of `install` :(

**Comment by dstroot** [comment]
Can confirm workaround works.  Thanks!

**Comment by joefitzgerald** [comment]
This is fixed in `go-plus` `4.1.0` https://github.com/joefitzgerald/go-plus/releases/tag/v4.1.0.
