### ISSUE TITLE
Linter options

### ISSUE THREAD

**Issue by sp-ruben-simon** [joefitzgerald/gometalinter-linter#56]
Hi, 

I'm not sure if this is a bug or I'm doing it wrong, but it's possible to set options for a specific linter?, like: `"--enable=errcheck -ignore Close"`

**Comment by lloiser** [comment]
Does `gometalinter` itself support this?
If so then try to add them in the settings of the `gometalinter-linter` package. There you can set the arguments passed to `gometalinter`.

**Comment by sp-ruben-simon** [comment]
I'm not able to make it work with gometalinter, so probably gometalinter doesn't support this.

thanks!
