### ISSUE TITLE
gometalinter detects ALL_CAPS constants insisting on camelCase

### ISSUE THREAD

**Issue by a-mstv** [joefitzgerald/gometalinter-linter#57]
As far as I'm aware ALL_CAPS **constants** are okay. I suppose this is an oversight then?

**Comment by joefitzgerald** [comment]
Can you paste a screenshot?

**Comment by a-mstv** [comment]
@joefitzgerald sure, here you go: https://i.imgur.com/ROoHHES.png

**Comment by joefitzgerald** [comment]
https://github.com/golang/lint/issues/32. This is coming from [`golint`](https://github.com/golang/lint). Your issue should probably be raised there, if it is an issue (https://github.com/golang/lint/issues?utf8=✓&q=is%3Aissue%20all_caps%20).

**Comment by a-mstv** [comment]
@joefitzgerald you're right, sorry I confused your work with golint.
